#!/usr/bin/tcsh -f
setenv TZ `readlink /etc/localtime | sed 's@/usr/share/zoneinfo/@@'`
docker run -it -e TZ=$TZ -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix:rw  -v /mnt/wslg:/mnt/wslg:rw mdmitry1/python313-dev:latest $*
