[build-system]
requires = ["setuptools>=80.10.1", "wheel","setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[project]
authors = [ {name = "Dmitry Messerman", email = "dmitry.messerman@gmail.com"} ]

name = "pyoptiwize"
dynamic = ["version"]
description = "Optimization tutorial: learn by example"
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }

dependencies = [
    "PySMT~=0.9.6",
    "deap~=1.4.3",
    "diversipy~=0.9",
    "onnxruntime~=1.23.2",
    "onnxscript~=0.5.7",
    "optproblems~=1.3",
    "optunahub~=0.4.0",
    "pandas~=2.3.3",
    "pandas-datareader~=0.10.0",
    "pkginfo~=1.12.1",
    "pymoo~=0.6.1",
    "pyomo~=6.9.5",
    "setuptools~=80.10.1",
    "shgo~=1.0.0",
    "tensorflow~=2.20.0",
    "tf2onnx~=1.17.0",
    "torch~=2.10.0",
    "scikit-learn~=1.8.0",
    "scikit-optimize~=0.10.2",
]

[project.optional-dependencies]
test = [
    "pytest~=9.0.3",
    "pytest-forked~=1.6.0",
    "pytest-mock~=3.15.1",
]

[tool.setuptools]
py-modules = []

[tool.setuptools.packages.find]
where = ["."]
include = ["pyoptiwize*"]

[tool.setuptools.data-files]
"bin" = ["bin/run_optimization_tutorial_examples"]

[tool.setuptools.package-data]
"pyoptiwize" = ["examples/**/*"]
