#!/usr/bin/tcsh -f
set script_path=`realpath $0 | xargs dirname`
set test=BNH
set test_lc=`echo $test | tr '[A-Z]' '[a-z]'`
set gzipped_dataset=${test_lc}.csv.gz 
if($#argv > 0) then
    if("-clean" == "$argv[1]") then
        \rm -f ${test}* *.log  >& /dev/null
        \rm -f $gzipped_dataset  >& /dev/null
        exit(0)
    endif
endif
${script_path}/bnh_dataset.py
set csv=${test}.csv
set json=${script_path}/${test_lc}_w.json
gunzip -c $gzipped_dataset > $csv
set noglob
set e1="F1*F1<1e-10 and (F2-50)*(F2-50)<1e-10"
set e2="(F1-0.692042)*(F1-0.692042)<1e-10 and (F2-44.290657)*(F2-44.290657)<1e-10"
set e3="(F1-4.081633)*(F1-4.081633)<1e-10 and (F2-36.734694)*(F2-36.734694)<1e-10"
set e4="(F1-14.876033)*(F1-14.876033)<1e-10 and (F2-26.446281)*(F2-26.446281)<1e-10"
set e5="(F1-50.0)*(F1-50.0)<1e-10 and (F2-12.5)*(F2-12.5)<1e-10"
set e6="(F1-136.0)*(F1-136.0)<1e-10 and (F2-4.0)*(F2-4.0)<1e-10"
set exprs=("$e1" "$e2" "$e3" "$e4" "$e5" "$e6")
python3.11 $script_path:h:h:h:h/src/run_smlp.py \
    -data $csv \
    -spec $json \
    -out_dir ./ \
    -pref $test \
    -mode certify \
    -quer_names query1,query2,query3,query4,query5,query6 \
    -quer_exprs "$e1;$e2;$e3;$e4;$e5;$e6" \
    -pareto f \
    -resp F1,F2 \
    -feat X1,X2 \
    -model poly_sklearn \
    -tree_encoding flat \
    -compress_rules t \
    -mrmr_pred 0 \
    -epsilon 0.000005 \
    -delta_rel 0.05 \
    -save_model t \
    -model_name $csv:r_model \
    -save_model_config t \
    -plots f \
    -pred_plots f \
    -resp_plots f \
    -seed 10 \
    -log_time f >& `realpath $0 | xargs basename`.log

foreach p (`seq 1 6`)
   echo $p $exprs[$p] `jq ".query${p}.witness_status" ${test}_${test}_certify_results.json`
end
