#!/usr/bin/tcsh -f
mkdir -p $HOME/shared
set ip=`hostname -I | tr ' ' '\n' | egrep -v '^172|^127|:|^$'`
set display=`echo $DISPLAY | cut -d: -f2`
pkill socat
socat TCP4-LISTEN:600${display},bind=$ip,reuseaddr,fork UNIX-CONNECT:/tmp/.X11-unix/X${display} &
setenv TZ `readlink /etc/localtime | sed 's@/usr/share/zoneinfo/@@'`
docker run -e DISPLAY=${ip}:${display} \
           -e TZ=$TZ \
           -e NO_AT_BRIDGE=1 \
           --network host \
           -v $HOME/shared:/shared \
           -it mdmitry1/python311-dev:latest $*
