#!/usr/bin/tcsh -f
mkdir -p $HOME/shared
if( ! $?TZ ) setenv TZ `readlink /etc/localtime | sed 's@/usr/share/zoneinfo/@@'`
docker run -e TZ=$TZ -e DISPLAY=:99 -p 5900:5900 -v $HOME/shared:/shared -it mdmitry1/python311-dev:latest $*
