#!/usr/bin/tcsh -f
./python-wget.py https://archives.boost.io/release/1.83.0/source/boost_1_83_0.tar.gz /tmp/boost_1_83_0.tar.gz
cd /tmp
tar -xvf boost_1_83_0.tar.gz >&  boost_1_83_0.tar.log
cd boost_1_83_0
./bootstrap.sh --with-python=/usr/bin/python3.11 --with-libraries=python
./b2 install --prefix=$HOME/boost_py311 --with-python python=3.11
cp -p $HOME/boost_py311/lib/libboost_python311.a /usr/lib/x86_64-linux-gnu
cp -p $HOME/boost_py311/lib/libboost_python311.so.1.83.0 /usr/lib/x86_64-linux-gnu
ln -s /usr/lib/x86_64-linux-gnu/{libboost_python311.so.1.83.0,libboost_python311.so}
