#!/usr/bin/tcsh -f
set log=`realpath $0 | xargs basename`.log
\rm -f $log >& /dev/null
docker run -it python311-dev smlp/src/run_smlp.py -h >& $log
if( 1 == `grep -c ^usage $log`) then
    echo "\nSMLP installation succeeded\n"
else
    echo "\nSMLP installation failed\n"
    exit(1)
endif
