#!/usr/bin/tcsh -f

# Copyright (C) 2025-2026 Dmitry Messerman
# SPDX-License-Identifier: GPL-3.0

set build_args=""
if($#argv > 0) then
    if("-rebuild" == "$argv[1]" ) then
        set build_args="--build-arg CACHE_BUST_OPTIMIZATION=`git ls-remote https://github.com/mdmitry1/optimization-tutorial refs/heads/main | cut -f1`"
    else
        echo "\nUsage: `realpath $0 | xargs basename` [-rebuild]\n"
        exit 0
    endif
endif
set cmd="env DOCKER_BUILDKIT=1 docker build $build_args --progress=plain -t optimization-tutorial ."
echo $cmd
$cmd
