#!/usr/bin/tcsh -f
set script_path=`realpath $0 | xargs dirname`
set test=smlp_toy_num_resp_mult
set log=${test}.log
set pref=Test83
if($#argv > 0 ) then
    if( '-clean' == "$argv[1]" ) then
        \rm -f *.log ${pref}_* >& /dev/null
        exit(0)
    endif
endif
if( 1 == `$script_path:h:h/src/run_smlp.py -h |& grep -c ^usage`) then
    echo "\nSMLP installation succeeded\n"
else
    echo "\nSMLP installation failed\n"
    exit(1)
endif
$script_path:h:h/src/run_smlp.py \
    -data ${test}.csv \
    -out_dir ./ \
    -pref $pref \
    -mode optimize -pareto t \
    -resp y1,y2 \
    -feat x,p1,p2 \
    -model dt_sklearn \
    -dt_sklearn_max_depth 15 \
    -spec ${test}_free_inps.json \
    -data_scaler min_max \
    -beta "y1>7 and y2>6" \
    -objv_names obj1,objv2,objv3 \
    -objv_exprs "(y1+y2)/2;y1/2-y2;y2" \
    -epsilon 0.05 \
    -delta_rel 0.01 \
    -save_model_config f \
    -mrmr_pred 0 \
    -plots f \
    -seed 10 \
    -log_time f \
