#!/usr/bin/tcsh -f
set script_path=`realpath $0 | xargs dirname`
if($#argv > 0) then
    if("-clean" == "$argv[1]") then
        \rm -f *.log  >& /dev/null
        exit(0)
    endif
endif
\ln -sf /usr/bin/python3.11 python3
if($PATH !~ \.*) then
    setenv PATH ".:${PATH}"
endif
set csv=c3dtlz4.csv
set json=$csv:r.json
$script_path:h:h:h:h/src/run_smlp.py -data $csv \
    -spec $script_path/$json \
    -out_dir ./ \
    -pref $csv:r \
    -mode optimize \
    -pareto t \
    -opt_strategy eager \
    -resp F1,F2 \
    -feat X0,X1,X2 \
    -model dt_sklearn \
    -dt_sklearn_max_depth 10 \
    -tree_encoding flat \
    -compress_rules t \
    -mrmr_pred 0 \
    -epsilon 0.0005 \
    -delta_rel 0.05 \
    -save_model t \
    -model_name $csv:r_model \
    -save_model_config t \
    -plots f \
    -pred_plots f \
    -resp_plots f \
    -seed 10 \
    -log_time f \
    >& `realpath $0 | xargs basename`.log
\rm -f python3
