#!/usr/bin/tcsh -f
set script_path=`realpath $0 | xargs dirname`
set test=s2_rx_anonym
set test_uc=`echo $test | tr '[a-z]' '[A-Z]'`
if($#argv > 0) then
    if("-clean" == "$argv[1]") then
        \rm -f ${test_uc}* *.log  >& /dev/null
        exit(0)
    endif
endif
onintr cleanup_handler
\ln -sf /usr/bin/python3.11 python3
if($PATH !~ \.*) then
    setenv PATH ".:${PATH}"
endif
set gzipped_dataset=${script_path}/${test}.csv.gz 
set csv=${script_path}/${test_uc}.csv
set json=${script_path}/${test}.json
gunzip -c $gzipped_dataset > $csv
$script_path:h:h:h:h/src/run_smlp.py -data $csv \
    -spec $json \
    -out_dir ./ \
    -pref $test_uc \
    -mode optimize \
    -pareto t \
    -opt_strategy lazy \
    -resp o0,o1 \
    -feat p0,p1,p2,p3,p4,p5,CH,RANK,Byte \
    -model dt_sklearn \
    -dt_sklearn_max_depth 15 \
    -tree_encoding flat \
    -compress_rules t \
    -mrmr_pred 0 \
    -epsilon 0.005 \
    -delta_abs 0 \
    -save_model t \
    -model_name $csv:r_model \
    -save_model_config t \
    -plots f \
    -pred_plots f \
    -resp_plots f \
    -seed 10 \
    -log_time f \
    >& `realpath $0 | xargs basename`.log
    \rm -f python3
exit($status)
cleanup_handler:
    \rm -f python3
