#!/usr/bin/tcsh -f
set script_path=`realpath $0 | xargs dirname`
${script_path}/run_s2_rx_anonym -clean
timeout 200 ${script_path}/run_s2_rx_anonym_311
if(-l python3) \rm -f python3
cat S2_RX_ANONYM_S2_RX_ANONYM_labeled_prediction_precisions.csv
if($#argv > 0) then
   if("-debug" == "$argv[1]") then
       exit(0)
   endif
endif
${script_path}/run_s2_rx_anonym_311 -clean
