#!/usr/bin/tcsh -f
set log=$PWD/`realpath $0 | xargs basename`.log
git rev-parse --show-toplevel >& /dev/null
if($status) then
    echo "\nERROR: Current directory s outside git directory tree\n"
    exit(1)
endif
if($#argv > 0) then
    if("-clean" == "$argv[1]") then
        cd `git rev-parse --show-toplevel`
        \rm -f regr_smlp/models/test{63,101}_model_y*_smlp_*
        \rm -rf regr_smlp/code/*{test,Test}*
        \rm -rf regr_smlp/code/{__pycache__,all_log.txt,logs.log,_doe.csv}
        exit(0)
    endif
endif
cd `git rev-parse --show-toplevel`/regr_smlp/code
echo "Log file: $log"
env CUDA_VISIBLE_DEVICES=-1 ./smlp_regr.py -w 8 -def n -t all -tol 7 |& tee $log
