#!/usr/bin/tcsh -f
foreach p ( `cut -d= -f1 python_packages_313.txt` )
    set s12=`grep ${p}= python_packages_312.txt`
    set s13=`grep ${p}= python_packages_313.txt`
    if( "" == "$s12" ) set s12="NONE"
    if( "" == "$s13" ) set s13="NONE"
    if ( "$s12" != "$s13" ) echo $s12 $s13
end
